#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  shift; shift

  export npm_config_registry="http://${CACHE_VIP}:4873/"
  export npm_config_ca=null
  npm install "$@"
  npm cache clean 
}

source sub "$0" "$@"
