#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  "$shome/script/update"

  nodeenv --prebuilt --node="$NODE_VERSION" "$shome/vendor/nodeenv-${NODE_VERSION}"
}

bootstrap
