#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  nvm install "${NODE_VERSION}"
  echo "${NODE_VERSION}" > "${BOARD_PATH}/.nvmrc"
}

bootstrap
