#!/usr/bin/env bash

function profile {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/bin:$shome/vendor/node/bin:$shome/node_modules/.bin:$PATH"

  export npm_config_cache="${BASEBOX_CACHE}/cache/npm"
}

profile
