#!/usr/bin/env bash

function _node_profile {
  local shome="${_node_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  export NODE_VERSION="${NODE_VERSION:-6.10.3}"

  if [[ -f "$shome/vendor/nodeenv/bin/activate" ]]; then
    set +u
    export NODE_VIRTUAL_ENV_DISABLE_PROMPT=1
		unset _OLD_NODE_PATH _OLD_NODE_VIRTUAL_PATH _OLD_NODE_VIRTUAL_PS1 _OLD_NPM_CONFIG_PREFIX _OLD_npm_config_prefix
    source "$shome/vendor/nodeenv/bin/activate"
		unset _OLD_NODE_PATH _OLD_NODE_VIRTUAL_PATH _OLD_NODE_VIRTUAL_PS1 _OLD_NPM_CONFIG_PREFIX _OLD_npm_config_prefix
  fi
}

_node_profile
