#!/usr/bin/env bash

function profile {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$shome/vendor/node/bin:$shome/node_modules/.bin:$PATH"
}

profile
