#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -n "${NODE_VERSION:-}" ]]; then
    if [[ "$(node --version 2>/dev/null | cut -b2-)" == "$NODE_VERSION" ]]; then
      if [[ -n "${NPM_VERSION:-}" ]]; then
        if [[ "$(npm --version 2>/dev/null)" == "$NPM_VERSION" ]]; then
          return 1
        fi
      else
        return 1
      fi
    fi
  elif [[ -x "$(type -P node)" ]]; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
