#!/usr/bin/env bash

function bootstrap {
  local shome="${_node_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  mkdir -p "${BASEBOX_CACHE}/cache/npm"
}

bootstrap
