#!/usr/bin/env bash

function node_version {
  local shome="${_node_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  local ver_node="$(node --version 2>&- | perl -pe 's{^v}{}' || true)"
  local ver_npm="$(npm --version 2>&- || true)"
  jq -n --arg node "$ver_node" \
        --arg npm "$ver_npm" \
        '{node: $node, npm: $npm}'
}

node_version "$@"
