#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_node="$(node --version 2>/dev/null | awk '{print $1}' | perl -pe 's{^v}{}' || true)"
  jq -n \
    --arg node "$ver_node" \
    '{node: $node}'
}

version "$@"
